//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JoinGo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.LoginLog = new HashSet<LoginLog>();
        }
    
        public int ACID { get; set; }
        public string Email { get; set; }
        public string PasswordHash { get; set; }
        public string EmailVerifyCode { get; set; }
        public bool EmailVerified { get; set; }
        public string Name { get; set; }
        public string Origin { get; set; }
        public string ProviderKey { get; set; }
        public string Role { get; set; }
        public string AvatarUrl { get; set; }
        public string Phone { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Company { get; set; }
        public string JobTitle { get; set; }
        public string EduLevel { get; set; }
        public string ContactName { get; set; }
        public string ContactPhone { get; set; }
        public Nullable<System.DateTime> LastPwdChange { get; set; }
        public Nullable<bool> PwdExpireNotified { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
        public bool Enable { get; set; }
        public Nullable<int> Creator { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedIP { get; set; }
        public Nullable<int> Updator { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public string UpdatedIP { get; set; }
        public string PasswordResetToken { get; set; }
        public Nullable<System.DateTime> PasswordResetExpiry { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoginLog> LoginLog { get; set; }
    }
}
