//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JoinGo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Activity()
        {
            this.Apply = new HashSet<Apply>();
        }
    
        public int ActID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> ApplyStartDate { get; set; }
        public Nullable<System.DateTime> ApplyEndDate { get; set; }
        public Nullable<int> Category { get; set; }
        public string Location { get; set; }
        public Nullable<int> Pay { get; set; }
        public Nullable<int> MaxParticipants { get; set; }
        public Nullable<int> WaitLimit { get; set; }
        public Nullable<int> CurrentCount { get; set; }
        public string PicFile { get; set; }
        public string Files { get; set; }
        public string Contact { get; set; }
        public string ContactPhone { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> AllowCancel { get; set; }
        public Nullable<int> CancelDeadlineDays { get; set; }
        public Nullable<int> ViewCount { get; set; }
        public Nullable<int> LikeCount { get; set; }
        public Nullable<int> Creator { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedIP { get; set; }
        public Nullable<int> Updator { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public string UpdatedIP { get; set; }
        public Nullable<int> SubCategory { get; set; }
    
        public virtual Category Category1 { get; set; }
        public virtual Category Category11 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Apply> Apply { get; set; }
    }
}
