//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JoinGo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apply
    {
        public int AID { get; set; }
        public int ActID { get; set; }
        public int ACID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Creator { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedIP { get; set; }
        public Nullable<int> Updator { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public string UpdatedIP { get; set; }
        public Nullable<System.DateTime> CanceledDate { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Activity Activity { get; set; }
    }
}
