//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JoinGo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public int QuID { get; set; }
        public int Type { get; set; }
        public string Questioner { get; set; }
        public string Email { get; set; }
        public string Question1 { get; set; }
        public string Response { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> IsTop { get; set; }
        public Nullable<int> Creator { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedIP { get; set; }
        public Nullable<int> Updator { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public string UpdatedIP { get; set; }
    }
}
